@startuml
struct RSJSONViewer {
    - jsonData: Data
    + init(json: String)
    + body: View
}

interface JSONElement {
    + render(): AnyView
    + renderCell(key: String): AnyView
}

struct JSONObjectView {
    - properties: [(String, JSONElement)]
}

struct JSONArrayView {
    - elements: [JSONElement]
}

struct JSONStringView {
    - value: String
}

struct JSONNumberView {
    - value: Double
}

struct JSONNullView {
    
}

struct JSONElementFactory {
    + create(from: Any): JSONElement
}

RSJSONViewer --> JSONElementFactory : "uses"
RSJSONViewer --> JSONElement : "parses"
JSONElement <|-- JSONObjectView
JSONElement <|-- JSONArrayView
JSONElement <|-- JSONStringView
JSONElement <|-- JSONNumberView
JSONElement <|-- JSONNullView
@enduml